# Generated by Django 5.2.1 on 2025-06-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_edited_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reply_to',
            new_name='parent_message',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', 'is_deleted'], name='chats_message_read_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sent_at'], name='chats_message_conv_sent_idx'),
        ),
    ]
