# Generated by Django 5.2.1 on 2025-06-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_rename_reply_to_message_parent_message_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='chats_message_read_deleted_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chats_message_conv_sent_idx',
        ),
    ]
