
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: messaging_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d messaging_app"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    environment:
      - ALLOWED_HOSTS=web,localhost,127.0.0.1,0.0.0.0
      - DATABASE_URL=postgres://postgres:admin1@db:5432/messaging_app
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: